source 'https://rubygems.org'
ruby '2.5.0'

gem 'sinatra', '~> 2.0.0'
gem 'sinatra-contrib'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'pg'
gem 'rake'
gem 'foreman'
gem 'rspec'
gem 'factory_bot'
gem 'faker'
